### ! realizar los seeders, solo se realizan una sola vez
GET http://localhost:8080/api/v1/seeders

### ! Listar todas las bodegas
GET  http://localhost:8080/api/v1/cellars

### ! Crear una bodega
POST http://localhost:8080/api/v1/cellars
Content-Type: application/json

{
    "name": "europe bodegas bs", 
    "userId": "1d24317e-5a63-4875-818b-6be0cf96aea7"
}

### ! Listar todos los productos
GET  http://localhost:8080/api/v1/products

### ! Crear un producto
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
    "name": "producto estrella 1", 
    "description": "Este es el mejor producto estrella 1"
}

### ! Crear un inventario con bodegaId y productId, (si existe toma el amount y lo suma con este nuevo que entra)
POST http://localhost:8080/api/v1/inventories
Content-Type: application/json

{
    "count": 5,
    "productId": "f5735c05-46d1-4019-bc17-677f247bc535",
    "cellarId": "89d524c1-1871-4acd-aa51-76a3279ab1c5"
}

### ! Permite mover cantidad de productos entre bodegas y generar un historial de movimientos 
POST http://localhost:8080/api/v1/inventories/move
Content-Type: application/json

{
    "count": 5,
    "cellarIdOrigin": "40eed4fd-9f90-45b8-ab77-e1b7ba61a45d",
    "cellarIdDestiny": "9032a571-c0bf-49f7-9c4c-4bfa26f907be", 
    "productId": "b0472a4c-85c3-41ae-b145-9d788b35e2b6"
}