### realizar los seeders, solo se realizan una sola vez
GET http://localhost:8080/api/v1/seeders

### Listar todas las bodegas
GET  http://localhost:8080/api/v1/cellars

### Crear una bodega
POST http://localhost:8080/api/v1/cellars
Content-Type: application/json

{
    "name": "europe bodegas bs", 
    "userId": "1d24317e-5a63-4875-818b-6be0cf96aea7"
}

### Listar todos los productos
GET  http://localhost:8080/api/v1/products

### Crear un producto
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
    "name": "producto estrella 1", 
    "description": "Este es el mejor producto estrella 1"
}

### Crear un inventario con bodegaId y productId, (si existe toma el amount y lo suma con este nuevo que entra)
POST http://localhost:8080/api/v1/inventories
Content-Type: application/json

{
    "count": 5,
    "productId": "f5735c05-46d1-4019-bc17-677f247bc535",
    "cellarId": "89d524c1-1871-4acd-aa51-76a3279ab1c5"
}